apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels: { app: node-exporter }
spec:
  selector:
    matchLabels: { app: node-exporter }
  template:
    metadata:
      labels: { app: node-exporter }
    spec:
      hostPID: true
      hostNetwork: false
      containers:
        - name: node-exporter
          image: docker.io/prom/node-exporter:v1.8.1
          imagePullPolicy: IfNotPresent
          args:
            - --path.rootfs=/host
          volumeMounts:
            - name: host
              mountPath: /host:ro
      volumes:
        - name: host
          hostPath:
            path: /
            type: Directory