apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podmonitors.monitoring.coreos.com
  annotations:
     argocd.argoproj.io/ignore-differences: |
      jqPathExpressions:
        - '.spec'
spec:
  group: monitoring.coreos.com
  scope: Namespaced
  names:
    plural: podmonitors
    singular: podmonitor
    kind: PodMonitor
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object